# Generated by Django 5.2.9 on 2025-12-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_desc', models.CharField(max_length=150)),
                ('exp_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exp_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inc_desc', models.CharField(max_length=150)),
                ('inc_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inc_date', models.DateField()),
            ],
        ),
    ]
